version: '3.3'
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
      image: carna9e/carnage_foodgram_backend:latest 
      env_file: .env
      volumes:
        - static_volume:/backend_static
        - media_volume:/app/media/
      depends_on:
        - db


  frontend:
    image: carna9e/carnage_foodgram_frontend:latest 
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - frontend_static:/frontend_static
    depends_on:
      - backend

  nginx:
    image: carna9e/carnage_foodgram_nginx:latest 
    env_file: .env
    ports:
      - 80:9090
    volumes:
      - frontend_static:/usr/share/nginx/html/
      - static_volume:/var/html/
      - media_volume:/var/html/media/
    depends_on:
      - frontend
    restart: always

volumes:
  pg_data:
  static_volume:
  media_volume:
  frontend_static: