# Generated by Django 3.2 on 2023-09-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_favoritedrecipe_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoritedRecipe',
        ),
    ]
