# Generated by Django 3.2 on 2023-09-19 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0015_favoritedrecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritedrecipe',
            options={'ordering': ('id',), 'verbose_name': 'Избранное'},
        ),
        migrations.RemoveField(
            model_name='favoritedrecipe',
            name='recipe',
        ),
        migrations.AddField(
            model_name='favoritedrecipe',
            name='favorited_recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_recipe', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='favoritedrecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='favoritedrecipe',
            constraint=models.UniqueConstraint(fields=('user', 'favorited_recipe'), name='unique favourited'),
        ),
    ]
