# Generated by Django 3.2 on 2023-10-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20231019_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
