# Generated by Django 3.2 on 2023-10-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20231029_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritedrecipe',
            options={'ordering': ('id',), 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.RemoveConstraint(
            model_name='favoritedrecipe',
            name='unique favourited',
        ),
        migrations.RemoveField(
            model_name='favoritedrecipe',
            name='favorited_recipe',
        ),
        migrations.AddField(
            model_name='favoritedrecipe',
            name='favorited_recipe',
            field=models.ManyToManyField(to='recipes.Recipe'),
        ),
    ]
