# Generated by Django 3.2 on 2023-10-31 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_auto_20231031_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritedrecipe',
            options={'ordering': ('id',), 'verbose_name': 'Избранное'},
        ),
        migrations.RemoveField(
            model_name='favoritedrecipe',
            name='favorited_recipe',
        ),
        migrations.AddField(
            model_name='favoritedrecipe',
            name='favorited_recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_recipe', to='recipes.recipe'),
        ),
        migrations.AddConstraint(
            model_name='favoritedrecipe',
            constraint=models.UniqueConstraint(fields=('user', 'favorited_recipe'), name='unique favourited'),
        ),
    ]
