# Generated by Django 3.2 on 2023-10-31 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_alter_favoritedrecipe_favorited_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritedrecipe',
            options={'ordering': ('id',), 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
    ]
