# Generated by Django 3.2 on 2023-10-31 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0026_alter_favoritedrecipe_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritedRecipe222',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_recipe222', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='ListFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_favorites2', models.ManyToManyField(through='recipes.FavoritedRecipe222', to='recipes.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Список избранных',
                'verbose_name_plural': 'Список избранных',
            },
        ),
        migrations.AddField(
            model_name='favoritedrecipe222',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_recipe222', to='recipes.listfavorites'),
        ),
        migrations.AddConstraint(
            model_name='favoritedrecipe222',
            constraint=models.UniqueConstraint(fields=('user', 'favorited_recipe'), name='unique favourited222'),
        ),
    ]
