# Generated by Django 3.2 on 2023-10-31 14:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0027_auto_20231031_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='ShoppingList',
        ),
        migrations.RemoveField(
            model_name='listfavorites',
            name='list_favorites2',
        ),
        migrations.RemoveField(
            model_name='listfavorites',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='favoritedrecipe',
            options={'ordering': ('id',), 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.DeleteModel(
            name='FavoritedRecipe222',
        ),
        migrations.DeleteModel(
            name='ListFavorites',
        ),
    ]
